-- ============================================================================
-- Juruweb Studio — readable project reference on every order
-- ============================================================================
-- Run in the Supabase SQL editor. Idempotent: running it twice is safe.
--
-- Orders are identified by a UUID, which nobody can read out over WhatsApp.
-- This adds a short reference like JW-0042 alongside it. The UUID stays the
-- primary key and every existing foreign key keeps working untouched.
-- ============================================================================

CREATE SEQUENCE IF NOT EXISTS public.order_ref_seq START 1;

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS project_ref TEXT;

-- Backfill oldest-first, so the numbers follow the order work actually came in.
DO $$
DECLARE
    r        RECORD;
    next_num BIGINT := 1;
BEGIN
    FOR r IN
        SELECT id FROM public.orders
        WHERE project_ref IS NULL
        ORDER BY created_at ASC, id ASC
    LOOP
        UPDATE public.orders
        SET project_ref = 'JW-' || lpad(next_num::TEXT, 4, '0')
        WHERE id = r.id;
        next_num := next_num + 1;
    END LOOP;

    -- Park the sequence past whatever was just assigned, so new orders carry on
    -- from there rather than colliding.
    PERFORM setval('public.order_ref_seq', GREATEST(next_num - 1, 1), TRUE);
END;
$$;

-- New rows get one automatically.
ALTER TABLE public.orders
    ALTER COLUMN project_ref
    SET DEFAULT 'JW-' || lpad(nextval('public.order_ref_seq')::TEXT, 4, '0');

-- Enforce uniqueness only now that every row has a value.
CREATE UNIQUE INDEX IF NOT EXISTS orders_project_ref_idx
    ON public.orders (project_ref);

COMMENT ON COLUMN public.orders.project_ref IS
  'Short human reference (JW-0001). Generated by order_ref_seq; the UUID id remains the key.';

GRANT USAGE, SELECT ON SEQUENCE public.order_ref_seq TO authenticated;
